version: '3'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5442:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: leximatedb
    volumes:
      - ./postgres:/var/lib/postgres/data
